# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bRQ2320V7k2Tx6BzWE_PZq5JzSkrHL-v
"""

pip install opencv-python

import cv2
rasm1=cv2.imread("kabutar.jpg")
rasm2=cv2.imread("tabiat.jfif")
rasm3=cv2.imread("3rasm.jpg")
cv2_imshow(rasm1)
cv2_imshow(rasm2)
cv2_imshow(rasm3)
oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
oqqora=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)